language: go

go:
  - 1.12
  - 1.13

env:
  - GO111MODULE=on

script:
  - go test -mod vendor -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)